-- OpenOps V1 core schema.
-- 权威来源：Obsidian 学习/OpenOps/19-PostgreSQL建表语句.md（自动提取，勿手改此文件，改 19 号后重新生成）。
-- ⚠ 本文件表名带 `sre_` 部署前缀（2026-07-11，内网共享 schema 隔离用）；Obsidian 19 号已同步套前缀，两者一致。
--   逻辑表名（无前缀）见 18 号数据模型；从 19 号重新生成即得带前缀 DDL，无需再手动加。
-- ⚠ GaussDB/openGauss 保留字：列 `role` 已改物理名 `user_role`（应用层经 `user_role AS role` 别名仍用逻辑名 role）。
--   换库前用 check-SQL 核单词列是否撞该库保留字（pg_get_keywords catcode='R'）：role/source/status/action/... 详见 34 号。
-- Rules: table links are checked in application code; UUIDs are generated by the application.

-- OpenOps V1 PostgreSQL DDL
-- Source: [[18-数据模型]]
-- 说明：本 DDL 不声明数据库级表间关联约束，不使用数据库自动回调机制。

CREATE TABLE IF NOT EXISTS sre_openops_user (
  user_id text NOT NULL PRIMARY KEY,
  user_role text NOT NULL,   -- 原名 role，因 GaussDB 保留字改名（2026-07-11）；应用层仍用逻辑名 role
  display_name text,
  email text,
  department_id text,
  status text NOT NULL DEFAULT 'active',
  last_login_at timestamptz,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_user_whitelist (
  whitelist_id uuid NOT NULL PRIMARY KEY,
  user_id text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  resource_profile text NOT NULL DEFAULT 'default',
  granted_by text,
  granted_at timestamptz NOT NULL DEFAULT now(),
  expire_at timestamptz,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_platform_runtime_config (
  config_id uuid NOT NULL PRIMARY KEY,
  config_domain text NOT NULL,
  config_key text NOT NULL,
  config_value_json jsonb NOT NULL,
  value_type text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  description text,
  updated_reason text,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_agent_team_template (
  template_id uuid NOT NULL PRIMARY KEY,
  template_key text NOT NULL,
  display_name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'draft',
  active_template_version_id uuid,
  created_by text NOT NULL,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_agent_team_template_version (
  template_version_id uuid NOT NULL PRIMARY KEY,
  template_id uuid NOT NULL,
  version_no integer NOT NULL,
  schema_version text NOT NULL,
  content_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft',
  published_by text,
  published_at timestamptz,
  content_hash text,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_agent_team_instance (
  agent_team_instance_id uuid NOT NULL PRIMARY KEY,
  owner_user_id text NOT NULL,
  template_id uuid NOT NULL,
  template_version_id uuid NOT NULL,
  instance_name text NOT NULL,
  workspace_id text NOT NULL,
  scope_revision text,
  active_config_version_id uuid,
  status text NOT NULL DEFAULT 'initializing',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_agent_team_config_version (
  config_version_id uuid NOT NULL PRIMARY KEY,
  agent_team_instance_id uuid NOT NULL,
  template_version_id uuid NOT NULL,
  version_no integer NOT NULL,
  schema_version text NOT NULL,
  overlay_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft',
  created_by text NOT NULL,
  creation_date timestamptz NOT NULL DEFAULT now(),
  change_reason text,
  overlay_hash text,
  last_update_date timestamptz NOT NULL DEFAULT now(),
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_instance_asset_binding (
  binding_id uuid NOT NULL PRIMARY KEY,
  agent_team_instance_id uuid NOT NULL,
  config_version_id uuid NOT NULL,
  owner_user_id text NOT NULL,
  agent_key text NOT NULL,
  asset_type text NOT NULL,
  skill_id uuid,
  skill_version_id uuid,
  mcp_id uuid,
  mcp_version_id uuid,
  status text NOT NULL DEFAULT 'enabled',
  created_by text NOT NULL,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz,
  -- 单表列组合约束（非外键、非触发器）；若倾向零 CHECK 可删除，应用层已有同等校验
  CONSTRAINT ck_asset_binding_type_columns CHECK (
    (asset_type = 'skill' AND skill_id IS NOT NULL AND mcp_id IS NULL)
    OR (asset_type = 'mcp' AND mcp_id IS NOT NULL AND skill_id IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS sre_skill_asset (
  skill_id uuid NOT NULL PRIMARY KEY,
  source text NOT NULL DEFAULT 'openops',
  source_type text NOT NULL,
  owner_user_id text,
  display_name text NOT NULL,
  skill_key text,
  tags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_skill_asset_version (
  skill_version_id uuid NOT NULL PRIMARY KEY,
  skill_id uuid NOT NULL,
  version_no integer NOT NULL,
  manifest_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  package_uri text,
  checksum_sha256 text,
  status text NOT NULL DEFAULT 'uploaded',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_mcp_asset (
  mcp_id uuid NOT NULL PRIMARY KEY,
  source text NOT NULL DEFAULT 'openops',
  source_type text NOT NULL,
  owner_user_id text,
  display_name text NOT NULL,
  transport text NOT NULL,
  endpoint_config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_mcp_asset_version (
  mcp_version_id uuid NOT NULL PRIMARY KEY,
  mcp_id uuid NOT NULL,
  version_no integer NOT NULL,
  manifest_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  package_uri text,
  checksum_sha256 text,
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_mcp_tool_catalog (
  tool_catalog_id uuid NOT NULL PRIMARY KEY,
  mcp_version_id uuid NOT NULL,
  tool_name text NOT NULL,
  description text,
  input_schema_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  schema_hash text,
  discovered_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_mcp_tool_annotation (
  annotation_id uuid NOT NULL PRIMARY KEY,
  tool_catalog_id uuid NOT NULL,
  is_approval_required boolean NOT NULL DEFAULT false,
  is_secret_required boolean NOT NULL DEFAULT false,
  scope_mode text NOT NULL DEFAULT 'none',
  appid_arg_path text,
  status text NOT NULL DEFAULT 'unreviewed',
  blocked_reason text,
  annotated_by text,
  annotated_at timestamptz,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz,
  -- 单表列组合约束（非外键、非触发器）；若倾向零 CHECK 可删除，应用层已有同等校验
  CONSTRAINT ck_mcp_tool_annot_scope_path CHECK (
    scope_mode <> 'required' OR appid_arg_path IS NOT NULL
  )
);

CREATE TABLE IF NOT EXISTS sre_user_secret (
  secret_ref_id uuid NOT NULL PRIMARY KEY,
  user_id text NOT NULL,
  secret_name text NOT NULL,
  secret_type text NOT NULL,
  provider text,
  ciphertext text NOT NULL,
  nonce text NOT NULL,
  key_version text NOT NULL,
  fingerprint text,
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_user_llm_config (
  llm_config_id uuid NOT NULL PRIMARY KEY,
  user_id text NOT NULL,
  display_name text NOT NULL,
  provider text NOT NULL,
  base_url text NOT NULL,
  model_name text NOT NULL,
  secret_ref_id uuid NOT NULL,
  context_window_tokens integer,
  max_output_tokens integer,
  temperature numeric(6,4),
  top_p numeric(6,4),
  timeout_ms integer,
  max_retries integer,
  supports_tool_calling boolean NOT NULL DEFAULT false,
  supports_streaming boolean NOT NULL DEFAULT true,
  supports_json_mode boolean,
  extra_params_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_model_asset (
  model_asset_id uuid NOT NULL PRIMARY KEY,
  display_name text NOT NULL,
  protocol text NOT NULL DEFAULT 'openai_compatible',
  model_id text NOT NULL,
  base_url text,
  secret_env_var text,
  access_scope text NOT NULL DEFAULT 'all',
  status text NOT NULL DEFAULT 'active',
  registered_by text NOT NULL,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_model_access_grant (
  grant_id uuid NOT NULL PRIMARY KEY,
  model_asset_id uuid NOT NULL,
  user_id text NOT NULL,
  granted_by text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_agent_run (
  agent_run_id uuid NOT NULL PRIMARY KEY,
  user_id text NOT NULL,
  agent_team_instance_id uuid NOT NULL,
  config_version_id uuid NOT NULL,
  framework_session_id text NOT NULL,
  scope_snapshot_id uuid,
  audit_trace_id uuid NOT NULL,
  run_title text,
  run_status text NOT NULL DEFAULT 'active',
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  status_reason_code text,
  status_message text,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_scope_snapshot (
  scope_snapshot_id uuid NOT NULL PRIMARY KEY,
  user_id text NOT NULL,
  agent_team_instance_id uuid NOT NULL,
  agent_run_id uuid NOT NULL,
  task_id text,
  workspace_id text NOT NULL,
  scope_revision text,
  effective_appids_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  omodel_request_id text,
  compute_reason text NOT NULL,
  computed_at timestamptz NOT NULL DEFAULT now(),
  creation_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_update_date timestamptz NOT NULL DEFAULT now(),
  last_updated_by text NOT NULL DEFAULT 'system',
  expire_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_approval_request (
  approval_request_id uuid NOT NULL PRIMARY KEY,
  user_id text NOT NULL,
  agent_team_instance_id uuid NOT NULL,
  agent_run_id uuid NOT NULL,
  framework_session_id text NOT NULL,
  reply_id text NOT NULL,
  tool_call_id text NOT NULL,
  tool_call_name text NOT NULL,
  task_id text,
  tool_catalog_id uuid,
  scope_snapshot_id uuid,
  arguments_redacted_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  suggested_rules_redacted_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  decision text NOT NULL DEFAULT 'pending',
  decided_by text,
  decided_at timestamptz,
  audit_trace_id uuid NOT NULL,
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL DEFAULT 'system',
  last_updated_by text NOT NULL DEFAULT 'system',
  expire_at timestamptz
);

CREATE TABLE IF NOT EXISTS sre_audit_event (
  audit_event_id uuid NOT NULL PRIMARY KEY,
  audit_trace_id uuid NOT NULL,
  span_id text,
  parent_span_id text,
  event_type text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor_type text NOT NULL,
  user_id text,
  agent_team_instance_id uuid,
  agent_run_id uuid,
  task_id text,
  config_version_id uuid,
  scope_snapshot_id uuid,
  target_type text,
  target_id text,
  action text NOT NULL,
  decision text,
  reason_code text,
  external_system text,
  external_request_id text,
  payload_redacted_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload_hash text,
  duration_ms bigint,
  created_by text NOT NULL DEFAULT 'system',
  creation_date timestamptz NOT NULL DEFAULT now(),
  last_update_date timestamptz NOT NULL DEFAULT now(),
  last_updated_by text NOT NULL DEFAULT 'system',
  expire_at timestamptz NOT NULL
);

-- 白名单一人一行（软删后可重新加白）
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_whitelist_user
  ON sre_user_whitelist (user_id)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_platform_runtime_config_key
  ON sre_platform_runtime_config (config_domain, config_key)
  WHERE deleted_at IS NULL;

-- 模型资产 model_id 未删行唯一；授权同一 (模型,用户) 未删行唯一（改授权=软删+插新，不原地改写）
CREATE UNIQUE INDEX IF NOT EXISTS ux_model_asset_model_id
  ON sre_model_asset (model_id)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_model_access_grant_user
  ON sre_model_access_grant (model_asset_id, user_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_model_access_grant_user
  ON sre_model_access_grant (user_id)
  WHERE deleted_at IS NULL;

-- 软删后 template_key 可复用，与实例 owner+name 的处理一致
CREATE UNIQUE INDEX IF NOT EXISTS ux_tpl_key
  ON sre_agent_team_template (template_key)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_tplver_no
  ON sre_agent_team_template_version (template_id, version_no);

-- 同一模板最多一个 active 版本：并发双发布是应用层校验挡不住的竞态，用部分唯一索引兜底（非外键、非触发器）
CREATE UNIQUE INDEX IF NOT EXISTS ux_tplver_active
  ON sre_agent_team_template_version (template_id)
  WHERE status = 'active';

CREATE UNIQUE INDEX IF NOT EXISTS ux_inst_owner_name
  ON sre_agent_team_instance (owner_user_id, instance_name)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_cfgver_no
  ON sre_agent_team_config_version (agent_team_instance_id, version_no);

-- 同一实例最多一个 active 配置版本：同上，部分唯一索引兜底并发双激活
CREATE UNIQUE INDEX IF NOT EXISTS ux_cfgver_active
  ON sre_agent_team_config_version (agent_team_instance_id)
  WHERE status = 'active';

CREATE UNIQUE INDEX IF NOT EXISTS ux_iab_skill
  ON sre_instance_asset_binding (config_version_id, skill_id)
  WHERE asset_type = 'skill' AND skill_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_iab_mcp
  ON sre_instance_asset_binding (config_version_id, mcp_id)
  WHERE asset_type = 'mcp' AND mcp_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_skill_asset_version_no
  ON sre_skill_asset_version (skill_id, version_no);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mcp_asset_version_no
  ON sre_mcp_asset_version (mcp_id, version_no);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mcp_tool_catalog_name
  ON sre_mcp_tool_catalog (mcp_version_id, tool_name);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mcp_tool_annotation_catalog
  ON sre_mcp_tool_annotation (tool_catalog_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_approval_request_tool_call
  ON sre_approval_request (agent_run_id, reply_id, tool_call_id);

CREATE INDEX IF NOT EXISTS ix_openops_user_status
  ON sre_openops_user (status);

CREATE INDEX IF NOT EXISTS ix_user_whitelist_user_status
  ON sre_user_whitelist (user_id, status);

CREATE INDEX IF NOT EXISTS ix_user_whitelist_expire_at
  ON sre_user_whitelist (expire_at);

CREATE INDEX IF NOT EXISTS ix_platform_runtime_config_status
  ON sre_platform_runtime_config (config_domain, status);

CREATE INDEX IF NOT EXISTS ix_tpl_status
  ON sre_agent_team_template (status);

CREATE INDEX IF NOT EXISTS ix_tplver_tpl_status
  ON sre_agent_team_template_version (template_id, status);

CREATE INDEX IF NOT EXISTS ix_inst_owner_status
  ON sre_agent_team_instance (owner_user_id, status);

CREATE INDEX IF NOT EXISTS ix_inst_workspace
  ON sre_agent_team_instance (workspace_id);

CREATE INDEX IF NOT EXISTS ix_cfgver_inst_status
  ON sre_agent_team_config_version (agent_team_instance_id, status);

CREATE INDEX IF NOT EXISTS ix_iab_cfg_status
  ON sre_instance_asset_binding (config_version_id, status);


CREATE INDEX IF NOT EXISTS ix_iab_skill_ref
  ON sre_instance_asset_binding (skill_id);

CREATE INDEX IF NOT EXISTS ix_iab_mcp_ref
  ON sre_instance_asset_binding (mcp_id);

CREATE INDEX IF NOT EXISTS ix_skill_asset_owner_status
  ON sre_skill_asset (owner_user_id, status);

CREATE INDEX IF NOT EXISTS ix_skill_asset_source_status
  ON sre_skill_asset (source, source_type, status);

CREATE INDEX IF NOT EXISTS ix_skillver_status
  ON sre_skill_asset_version (skill_id, status);

CREATE INDEX IF NOT EXISTS ix_skillver_checksum
  ON sre_skill_asset_version (checksum_sha256);

CREATE INDEX IF NOT EXISTS ix_mcp_asset_owner_status
  ON sre_mcp_asset (owner_user_id, status);

CREATE INDEX IF NOT EXISTS ix_mcp_asset_source_status
  ON sre_mcp_asset (source, source_type, status);

CREATE INDEX IF NOT EXISTS ix_mcpver_status
  ON sre_mcp_asset_version (mcp_id, status);

CREATE INDEX IF NOT EXISTS ix_mcp_tool_catalog_status
  ON sre_mcp_tool_catalog (status);

CREATE INDEX IF NOT EXISTS ix_mcp_tool_annotation_status
  ON sre_mcp_tool_annotation (status);

CREATE INDEX IF NOT EXISTS ix_user_secret_user_status
  ON sre_user_secret (user_id, status);

CREATE INDEX IF NOT EXISTS ix_user_secret_fingerprint
  ON sre_user_secret (fingerprint);

CREATE INDEX IF NOT EXISTS ix_user_llm_config_user_status
  ON sre_user_llm_config (user_id, status);

CREATE INDEX IF NOT EXISTS ix_user_llm_config_secret
  ON sre_user_llm_config (secret_ref_id);

CREATE INDEX IF NOT EXISTS ix_agent_run_user_started
  ON sre_agent_run (user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS ix_agent_run_instance_started
  ON sre_agent_run (agent_team_instance_id, started_at DESC);

CREATE INDEX IF NOT EXISTS ix_agent_run_status
  ON sre_agent_run (run_status);

CREATE INDEX IF NOT EXISTS ix_agent_run_trace
  ON sre_agent_run (audit_trace_id);

CREATE INDEX IF NOT EXISTS ix_agent_run_framework_session
  ON sre_agent_run (framework_session_id);

CREATE INDEX IF NOT EXISTS ix_scope_snapshot_run_time
  ON sre_scope_snapshot (agent_run_id, computed_at DESC);

CREATE INDEX IF NOT EXISTS ix_scope_snapshot_user_time
  ON sre_scope_snapshot (user_id, computed_at DESC);

CREATE INDEX IF NOT EXISTS ix_scope_inst_time
  ON sre_scope_snapshot (agent_team_instance_id, computed_at DESC);

CREATE INDEX IF NOT EXISTS ix_scope_snapshot_workspace
  ON sre_scope_snapshot (workspace_id, scope_revision);

CREATE INDEX IF NOT EXISTS ix_scope_snapshot_expire_at
  ON sre_scope_snapshot (expire_at);

CREATE INDEX IF NOT EXISTS ix_appr_run_decision
  ON sre_approval_request (agent_run_id, decision);

CREATE INDEX IF NOT EXISTS ix_appr_user_created
  ON sre_approval_request (user_id, creation_date DESC);

CREATE INDEX IF NOT EXISTS ix_appr_trace
  ON sre_approval_request (audit_trace_id);

-- expire_at 仅服务 pending 超时扫描，部分索引更小更准
CREATE INDEX IF NOT EXISTS ix_appr_pending_expire
  ON sre_approval_request (expire_at)
  WHERE decision = 'pending';

CREATE INDEX IF NOT EXISTS ix_audit_event_trace_time
  ON sre_audit_event (audit_trace_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_event_run_time
  ON sre_audit_event (agent_run_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_event_user_time
  ON sre_audit_event (user_id, occurred_at DESC);


-- 审计查询 API 支持按 event_type 过滤（见 21 号审计回放接口）
CREATE INDEX IF NOT EXISTS ix_audit_event_type_time
  ON sre_audit_event (event_type, occurred_at DESC);


CREATE INDEX IF NOT EXISTS ix_audit_event_expire_at
  ON sre_audit_event (expire_at);

COMMENT ON TABLE sre_openops_user IS 'OpenOps 用户表，user_id 为 W3 工号';
COMMENT ON COLUMN sre_openops_user.user_id IS '用户主键，W3 工号';
COMMENT ON COLUMN sre_openops_user.user_role IS '角色：user / platform_admin（原名 role，GaussDB 保留字改名）';
COMMENT ON COLUMN sre_openops_user.display_name IS '用户展示名';
COMMENT ON COLUMN sre_openops_user.email IS '邮箱';
COMMENT ON COLUMN sre_openops_user.department_id IS '部门 ID，可空';
COMMENT ON COLUMN sre_openops_user.status IS '状态：active / disabled / deleted';
COMMENT ON COLUMN sre_openops_user.last_login_at IS '最近登录时间';
COMMENT ON COLUMN sre_openops_user.creation_date IS '创建时间';
COMMENT ON COLUMN sre_openops_user.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_openops_user.created_by IS '创建人工号';
COMMENT ON COLUMN sre_openops_user.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_openops_user.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_user_whitelist IS 'V1 试点白名单';
COMMENT ON COLUMN sre_user_whitelist.whitelist_id IS '白名单主键';
COMMENT ON COLUMN sre_user_whitelist.user_id IS '用户 W3 工号';
COMMENT ON COLUMN sre_user_whitelist.status IS '状态：active / disabled / deleted';
COMMENT ON COLUMN sre_user_whitelist.resource_profile IS '资源规格档位，如 default / large';
COMMENT ON COLUMN sre_user_whitelist.granted_by IS '授权管理员工号';
COMMENT ON COLUMN sre_user_whitelist.granted_at IS '授权时间';
COMMENT ON COLUMN sre_user_whitelist.expire_at IS '白名单过期时间，可空';
COMMENT ON COLUMN sre_user_whitelist.creation_date IS '创建时间';
COMMENT ON COLUMN sre_user_whitelist.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_user_whitelist.created_by IS '创建人工号';
COMMENT ON COLUMN sre_user_whitelist.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_user_whitelist.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_platform_runtime_config IS '平台运行配置表，用于管理台控制沙箱容量、idle TTL 和默认资源配额';
COMMENT ON COLUMN sre_platform_runtime_config.config_id IS '配置主键';
COMMENT ON COLUMN sre_platform_runtime_config.config_domain IS '配置域，V1 使用 sandbox / platform_model';
COMMENT ON COLUMN sre_platform_runtime_config.config_key IS '配置 key，如 max_user_containers_per_host';
COMMENT ON COLUMN sre_platform_runtime_config.config_value_json IS '配置值，JSON 保存 number / string / boolean / object';
COMMENT ON COLUMN sre_platform_runtime_config.value_type IS 'integer / number / string / boolean / object';
COMMENT ON COLUMN sre_platform_runtime_config.status IS 'active / disabled / deleted';
COMMENT ON COLUMN sre_platform_runtime_config.description IS '配置说明';
COMMENT ON COLUMN sre_platform_runtime_config.updated_reason IS '管理员修改原因';
COMMENT ON COLUMN sre_platform_runtime_config.creation_date IS '创建时间';
COMMENT ON COLUMN sre_platform_runtime_config.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_platform_runtime_config.created_by IS '创建人工号';
COMMENT ON COLUMN sre_platform_runtime_config.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_platform_runtime_config.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_agent_team_template IS '平台管理员维护的 AgentTeam 模板主表';
COMMENT ON COLUMN sre_agent_team_template.template_id IS '模板主键';
COMMENT ON COLUMN sre_agent_team_template.template_key IS '模板稳定 key';
COMMENT ON COLUMN sre_agent_team_template.display_name IS '模板展示名';
COMMENT ON COLUMN sre_agent_team_template.description IS '模板描述';
COMMENT ON COLUMN sre_agent_team_template.status IS '状态：draft / active / disabled / deleted';
COMMENT ON COLUMN sre_agent_team_template.active_template_version_id IS '当前 active 模板版本 ID，应用层维护';
COMMENT ON COLUMN sre_agent_team_template.created_by IS '创建人工号';
COMMENT ON COLUMN sre_agent_team_template.creation_date IS '创建时间';
COMMENT ON COLUMN sre_agent_team_template.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_agent_team_template.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_agent_team_template.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_agent_team_template_version IS '不可变模板版本，保存 main/sub 定义和模板默认资产绑定';
COMMENT ON COLUMN sre_agent_team_template_version.template_version_id IS '模板版本主键';
COMMENT ON COLUMN sre_agent_team_template_version.template_id IS '所属模板 ID';
COMMENT ON COLUMN sre_agent_team_template_version.version_no IS '版本号，模板内递增';
COMMENT ON COLUMN sre_agent_team_template_version.schema_version IS 'content_json 的 schema 版本';
COMMENT ON COLUMN sre_agent_team_template_version.content_json IS '模板内容 JSON，含 main/sub role、模板级 LLM、平台 Skill/MCP tool 绑定';
COMMENT ON COLUMN sre_agent_team_template_version.status IS '状态：draft / active / archived / disabled / deleted';
COMMENT ON COLUMN sre_agent_team_template_version.published_by IS '发布管理员工号';
COMMENT ON COLUMN sre_agent_team_template_version.published_at IS '发布时间';
COMMENT ON COLUMN sre_agent_team_template_version.content_hash IS '内容 hash';
COMMENT ON COLUMN sre_agent_team_template_version.creation_date IS '创建时间';
COMMENT ON COLUMN sre_agent_team_template_version.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_agent_team_template_version.created_by IS '创建人工号';
COMMENT ON COLUMN sre_agent_team_template_version.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_agent_team_template_version.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_agent_team_instance IS '普通用户基于模板创建的 AgentTeam 实例';
COMMENT ON COLUMN sre_agent_team_instance.agent_team_instance_id IS '实例主键';
COMMENT ON COLUMN sre_agent_team_instance.owner_user_id IS '实例所属 W3 工号';
COMMENT ON COLUMN sre_agent_team_instance.template_id IS '来源模板 ID';
COMMENT ON COLUMN sre_agent_team_instance.template_version_id IS '创建时锁定的模板版本 ID';
COMMENT ON COLUMN sre_agent_team_instance.instance_name IS '用户可见实例名';
COMMENT ON COLUMN sre_agent_team_instance.workspace_id IS 'omodel 工作范围唯一标识';
COMMENT ON COLUMN sre_agent_team_instance.scope_revision IS 'OpenOps 最近确认的 workspace 版本';
COMMENT ON COLUMN sre_agent_team_instance.active_config_version_id IS '当前 active 配置版本 ID';
COMMENT ON COLUMN sre_agent_team_instance.status IS '状态：initializing / active / disabled / deleted';
COMMENT ON COLUMN sre_agent_team_instance.creation_date IS '创建时间';
COMMENT ON COLUMN sre_agent_team_instance.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_agent_team_instance.created_by IS '创建人工号';
COMMENT ON COLUMN sre_agent_team_instance.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_agent_team_instance.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_agent_team_config_version IS '不可变实例配置版本，保存用户 overlay';
COMMENT ON COLUMN sre_agent_team_config_version.config_version_id IS '配置版本主键';
COMMENT ON COLUMN sre_agent_team_config_version.agent_team_instance_id IS '所属实例 ID';
COMMENT ON COLUMN sre_agent_team_config_version.template_version_id IS '基于的模板版本 ID';
COMMENT ON COLUMN sre_agent_team_config_version.version_no IS '版本号，实例内递增';
COMMENT ON COLUMN sre_agent_team_config_version.schema_version IS 'overlay_json 的 schema 版本';
COMMENT ON COLUMN sre_agent_team_config_version.overlay_json IS '用户 LLM、main role 追加等实例级配置';
COMMENT ON COLUMN sre_agent_team_config_version.status IS '状态：draft / active / archived / disabled / deleted';
COMMENT ON COLUMN sre_agent_team_config_version.created_by IS '创建人工号';
COMMENT ON COLUMN sre_agent_team_config_version.creation_date IS '创建时间';
COMMENT ON COLUMN sre_agent_team_config_version.change_reason IS '变更说明';
COMMENT ON COLUMN sre_agent_team_config_version.overlay_hash IS 'overlay 内容 hash';
COMMENT ON COLUMN sre_agent_team_config_version.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_agent_team_config_version.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_agent_team_config_version.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_instance_asset_binding IS '用户自定义 Skill/MCP 与 AgentTeam 实例配置版本的装配关系';
COMMENT ON COLUMN sre_instance_asset_binding.binding_id IS '绑定主键';
COMMENT ON COLUMN sre_instance_asset_binding.agent_team_instance_id IS '所属实例 ID';
COMMENT ON COLUMN sre_instance_asset_binding.config_version_id IS '所属配置版本 ID';
COMMENT ON COLUMN sre_instance_asset_binding.owner_user_id IS '资产 owner 工号，必须等于实例 owner';
COMMENT ON COLUMN sre_instance_asset_binding.agent_key IS '目标 Agent，V1 固定为 main';
COMMENT ON COLUMN sre_instance_asset_binding.asset_type IS '资产类型：skill / mcp';
COMMENT ON COLUMN sre_instance_asset_binding.skill_id IS '用户 Skill 资产 ID，asset_type=skill 时必填';
COMMENT ON COLUMN sre_instance_asset_binding.skill_version_id IS '用户 Skill 版本 ID，asset_type=skill 时必填';
COMMENT ON COLUMN sre_instance_asset_binding.mcp_id IS '用户 MCP 资产 ID，asset_type=mcp 时必填';
COMMENT ON COLUMN sre_instance_asset_binding.mcp_version_id IS '用户 MCP 版本 ID，asset_type=mcp 时必填';
COMMENT ON COLUMN sre_instance_asset_binding.status IS '状态：enabled / disabled / deleted';
COMMENT ON COLUMN sre_instance_asset_binding.created_by IS '创建人工号';
COMMENT ON COLUMN sre_instance_asset_binding.creation_date IS '创建时间';
COMMENT ON COLUMN sre_instance_asset_binding.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_instance_asset_binding.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_instance_asset_binding.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_skill_asset IS 'Skill 资产缓存，外部 Skill Hub 为事实源';
COMMENT ON COLUMN sre_skill_asset.skill_id IS 'Skill 资产主键';
COMMENT ON COLUMN sre_skill_asset.source IS '项目来源，V1 固定 openops';
COMMENT ON COLUMN sre_skill_asset.source_type IS '资产来源：platform / user';
COMMENT ON COLUMN sre_skill_asset.owner_user_id IS '用户 Skill owner 工号，平台 Skill 为空';
COMMENT ON COLUMN sre_skill_asset.display_name IS '展示名，可重复';
COMMENT ON COLUMN sre_skill_asset.skill_key IS '可选稳定 key';
COMMENT ON COLUMN sre_skill_asset.tags_json IS '业务标签数组，不用于识别 OpenOps 项目来源';
COMMENT ON COLUMN sre_skill_asset.status IS '状态：active / disabled / deleted';
COMMENT ON COLUMN sre_skill_asset.creation_date IS '创建时间';
COMMENT ON COLUMN sre_skill_asset.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_skill_asset.created_by IS '创建人工号';
COMMENT ON COLUMN sre_skill_asset.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_skill_asset.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_skill_asset_version IS 'Skill 版本缓存';
COMMENT ON COLUMN sre_skill_asset_version.skill_version_id IS 'Skill 版本主键';
COMMENT ON COLUMN sre_skill_asset_version.skill_id IS '所属 Skill ID';
COMMENT ON COLUMN sre_skill_asset_version.version_no IS '版本号';
COMMENT ON COLUMN sre_skill_asset_version.manifest_json IS 'Skill manifest';
COMMENT ON COLUMN sre_skill_asset_version.package_uri IS '包地址';
COMMENT ON COLUMN sre_skill_asset_version.checksum_sha256 IS '包 SHA-256 校验值';
COMMENT ON COLUMN sre_skill_asset_version.status IS '状态：uploaded / validated / enabled / disabled / deleted';
COMMENT ON COLUMN sre_skill_asset_version.creation_date IS '创建时间';
COMMENT ON COLUMN sre_skill_asset_version.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_skill_asset_version.created_by IS '创建人工号';
COMMENT ON COLUMN sre_skill_asset_version.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_skill_asset_version.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_mcp_asset IS 'MCP 资产缓存';
COMMENT ON COLUMN sre_mcp_asset.mcp_id IS 'MCP 资产主键';
COMMENT ON COLUMN sre_mcp_asset.source IS '项目来源，V1 固定 openops';
COMMENT ON COLUMN sre_mcp_asset.source_type IS '资产来源：platform / user';
COMMENT ON COLUMN sre_mcp_asset.owner_user_id IS '用户 MCP owner 工号，平台 MCP 为空';
COMMENT ON COLUMN sre_mcp_asset.display_name IS '展示名';
COMMENT ON COLUMN sre_mcp_asset.transport IS '传输方式，V1 only http；stdio / command 后续评估';
COMMENT ON COLUMN sre_mcp_asset.endpoint_config_json IS 'endpoint 或启动配置，必须脱敏';
COMMENT ON COLUMN sre_mcp_asset.status IS '状态：active / disabled / deleted';
COMMENT ON COLUMN sre_mcp_asset.creation_date IS '创建时间';
COMMENT ON COLUMN sre_mcp_asset.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_mcp_asset.created_by IS '创建人工号';
COMMENT ON COLUMN sre_mcp_asset.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_mcp_asset.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_mcp_asset_version IS 'MCP 版本缓存';
COMMENT ON COLUMN sre_mcp_asset_version.mcp_version_id IS 'MCP 版本主键';
COMMENT ON COLUMN sre_mcp_asset_version.mcp_id IS '所属 MCP ID';
COMMENT ON COLUMN sre_mcp_asset_version.version_no IS '版本号';
COMMENT ON COLUMN sre_mcp_asset_version.manifest_json IS 'MCP manifest';
COMMENT ON COLUMN sre_mcp_asset_version.package_uri IS '包地址';
COMMENT ON COLUMN sre_mcp_asset_version.checksum_sha256 IS '包 SHA-256 校验值';
COMMENT ON COLUMN sre_mcp_asset_version.status IS '状态：active / disabled / deleted';
COMMENT ON COLUMN sre_mcp_asset_version.creation_date IS '创建时间';
COMMENT ON COLUMN sre_mcp_asset_version.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_mcp_asset_version.created_by IS '创建人工号';
COMMENT ON COLUMN sre_mcp_asset_version.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_mcp_asset_version.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_mcp_tool_catalog IS 'MCP list_tools 发现结果';
COMMENT ON COLUMN sre_mcp_tool_catalog.tool_catalog_id IS 'tool catalog 主键';
COMMENT ON COLUMN sre_mcp_tool_catalog.mcp_version_id IS '所属 MCP 版本 ID';
COMMENT ON COLUMN sre_mcp_tool_catalog.tool_name IS 'MCP tool 名称';
COMMENT ON COLUMN sre_mcp_tool_catalog.description IS 'tool 描述';
COMMENT ON COLUMN sre_mcp_tool_catalog.input_schema_json IS 'MCP tool 输入 schema';
COMMENT ON COLUMN sre_mcp_tool_catalog.schema_hash IS 'input_schema 的 hash，OpenOps 自算，用于检测 tool schema 变化';
COMMENT ON COLUMN sre_mcp_tool_catalog.discovered_at IS 'list_tools 发现时间';
COMMENT ON COLUMN sre_mcp_tool_catalog.status IS '状态：active / removed / disabled';
COMMENT ON COLUMN sre_mcp_tool_catalog.creation_date IS '创建时间';
COMMENT ON COLUMN sre_mcp_tool_catalog.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_mcp_tool_catalog.created_by IS '创建人工号';
COMMENT ON COLUMN sre_mcp_tool_catalog.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_mcp_tool_catalog.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_mcp_tool_annotation IS '平台 MCP tool 管理员标注';
COMMENT ON COLUMN sre_mcp_tool_annotation.annotation_id IS '标注主键';
COMMENT ON COLUMN sre_mcp_tool_annotation.tool_catalog_id IS '所属 tool catalog ID';
COMMENT ON COLUMN sre_mcp_tool_annotation.is_approval_required IS '是否需要 AgentScope ASK';
COMMENT ON COLUMN sre_mcp_tool_annotation.is_secret_required IS '是否需要 SecretRef';
COMMENT ON COLUMN sre_mcp_tool_annotation.scope_mode IS 'none / optional / required';
COMMENT ON COLUMN sre_mcp_tool_annotation.appid_arg_path IS 'scope required 时必填，表示 APPID 入参路径';
COMMENT ON COLUMN sre_mcp_tool_annotation.status IS 'unreviewed / allowed / blocked，默认 unreviewed 运行时阻断';
COMMENT ON COLUMN sre_mcp_tool_annotation.blocked_reason IS '阻断原因，可空';
COMMENT ON COLUMN sre_mcp_tool_annotation.annotated_by IS '标注管理员工号';
COMMENT ON COLUMN sre_mcp_tool_annotation.annotated_at IS '标注时间';
COMMENT ON COLUMN sre_mcp_tool_annotation.creation_date IS '创建时间';
COMMENT ON COLUMN sre_mcp_tool_annotation.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_mcp_tool_annotation.created_by IS '创建人工号';
COMMENT ON COLUMN sre_mcp_tool_annotation.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_mcp_tool_annotation.deleted_at IS '软删除时间，NULL 表示未删除';
COMMENT ON COLUMN sre_mcp_tool_annotation.scope_mode IS 'none / optional / required';

COMMENT ON TABLE sre_user_secret IS '用户 Secret 密文表，明文不可回显';
COMMENT ON COLUMN sre_user_secret.secret_ref_id IS 'SecretRef 主键';
COMMENT ON COLUMN sre_user_secret.user_id IS '所属用户工号';
COMMENT ON COLUMN sre_user_secret.secret_name IS '用户可见名称';
COMMENT ON COLUMN sre_user_secret.secret_type IS 'llm_api_key / mcp_token / other';
COMMENT ON COLUMN sre_user_secret.provider IS 'provider 标识';
COMMENT ON COLUMN sre_user_secret.ciphertext IS '应用层加密后的密文，base64 文本编码';
COMMENT ON COLUMN sre_user_secret.nonce IS '加密 nonce / iv，base64 文本编码';
COMMENT ON COLUMN sre_user_secret.key_version IS '加密 key 版本';
COMMENT ON COLUMN sre_user_secret.fingerprint IS '脱敏指纹';
COMMENT ON COLUMN sre_user_secret.status IS 'active / disabled / deleted / rotation_required';
COMMENT ON COLUMN sre_user_secret.creation_date IS '创建时间';
COMMENT ON COLUMN sre_user_secret.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_user_secret.last_used_at IS '最近使用时间';
COMMENT ON COLUMN sre_user_secret.created_by IS '创建人工号';
COMMENT ON COLUMN sre_user_secret.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_user_secret.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_user_llm_config IS '用户 LLM endpoint、模型参数和 SecretRef 配置';
COMMENT ON COLUMN sre_user_llm_config.llm_config_id IS 'LLM 配置主键';
COMMENT ON COLUMN sre_user_llm_config.user_id IS '所属用户工号';
COMMENT ON COLUMN sre_user_llm_config.display_name IS '配置名称';
COMMENT ON COLUMN sre_user_llm_config.provider IS 'openai_compatible / custom / internal';
COMMENT ON COLUMN sre_user_llm_config.base_url IS 'LLM endpoint';
COMMENT ON COLUMN sre_user_llm_config.model_name IS '模型名';
COMMENT ON COLUMN sre_user_llm_config.secret_ref_id IS '引用的用户 SecretRef ID';
COMMENT ON COLUMN sre_user_llm_config.context_window_tokens IS '模型上下文窗口 token 上限';
COMMENT ON COLUMN sre_user_llm_config.max_output_tokens IS '单次最大输出 token';
COMMENT ON COLUMN sre_user_llm_config.temperature IS '采样温度，可空';
COMMENT ON COLUMN sre_user_llm_config.top_p IS '采样 top_p，可空';
COMMENT ON COLUMN sre_user_llm_config.timeout_ms IS '模型调用超时毫秒';
COMMENT ON COLUMN sre_user_llm_config.max_retries IS '模型调用重试次数';
COMMENT ON COLUMN sre_user_llm_config.supports_tool_calling IS '是否支持 tool calling';
COMMENT ON COLUMN sre_user_llm_config.supports_streaming IS '是否支持流式输出';
COMMENT ON COLUMN sre_user_llm_config.supports_json_mode IS '是否支持 JSON mode，可空';
COMMENT ON COLUMN sre_user_llm_config.extra_params_json IS 'Provider 差异化参数，不允许保存密钥';
COMMENT ON COLUMN sre_user_llm_config.status IS '状态：active / disabled / deleted';
COMMENT ON COLUMN sre_user_llm_config.creation_date IS '创建时间';
COMMENT ON COLUMN sre_user_llm_config.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_user_llm_config.created_by IS '创建人工号';
COMMENT ON COLUMN sre_user_llm_config.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_user_llm_config.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_model_asset IS '平台/部门注册的模型接口资产（管理台「模型资产」页；2026-07-09 自 sre_platform_runtime_config platform_model 域迁移）';
COMMENT ON COLUMN sre_model_asset.model_asset_id IS '模型资产主键';
COMMENT ON COLUMN sre_model_asset.display_name IS '展示名，如「交易大模型-TX」';
COMMENT ON COLUMN sre_model_asset.protocol IS '协议，V1 固定 openai_compatible';
COMMENT ON COLUMN sre_model_asset.model_id IS '模型标识（如 glm-5.1），未删行内全局唯一';
COMMENT ON COLUMN sre_model_asset.base_url IS 'OpenAI 兼容 endpoint，可空';
COMMENT ON COLUMN sre_model_asset.secret_env_var IS '平台侧 API Key 环境变量名，Key 本身不落库';
COMMENT ON COLUMN sre_model_asset.access_scope IS 'all=全员开放 / restricted=仅白名单授权用户（按人，不按部门）';
COMMENT ON COLUMN sre_model_asset.status IS '状态：active / disabled';
COMMENT ON COLUMN sre_model_asset.registered_by IS '注册人（管理员工号），管理台「归属」展示来源';
COMMENT ON COLUMN sre_model_asset.creation_date IS '创建时间';
COMMENT ON COLUMN sre_model_asset.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_model_asset.created_by IS '创建人工号';
COMMENT ON COLUMN sre_model_asset.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_model_asset.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_model_access_grant IS '模型白名单授权（按 user_id 逐人授权，仅 restricted 模型消费）';
COMMENT ON COLUMN sre_model_access_grant.grant_id IS '授权主键';
COMMENT ON COLUMN sre_model_access_grant.model_asset_id IS '关联模型资产 ID';
COMMENT ON COLUMN sre_model_access_grant.user_id IS '被授权用户工号';
COMMENT ON COLUMN sre_model_access_grant.granted_by IS '授权人（管理员工号）';
COMMENT ON COLUMN sre_model_access_grant.status IS '状态：active / revoked';
COMMENT ON COLUMN sre_model_access_grant.creation_date IS '创建时间';
COMMENT ON COLUMN sre_model_access_grant.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_model_access_grant.created_by IS '创建人工号';
COMMENT ON COLUMN sre_model_access_grant.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_model_access_grant.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_agent_run IS 'OpenOps 对 AgentScope 运行态的业务索引';
COMMENT ON COLUMN sre_agent_run.agent_run_id IS '运行索引主键';
COMMENT ON COLUMN sre_agent_run.user_id IS '运行发起人工号';
COMMENT ON COLUMN sre_agent_run.agent_team_instance_id IS '所属实例 ID';
COMMENT ON COLUMN sre_agent_run.config_version_id IS '运行使用的配置版本 ID';
COMMENT ON COLUMN sre_agent_run.framework_session_id IS 'AgentScope session ID';
COMMENT ON COLUMN sre_agent_run.scope_snapshot_id IS '最近一次范围快照 ID';
COMMENT ON COLUMN sre_agent_run.audit_trace_id IS 'OpenOps 根 trace';
COMMENT ON COLUMN sre_agent_run.run_status IS 'active / closed / blocked / completed / failed / deleted';
COMMENT ON COLUMN sre_agent_run.started_at IS '运行开始时间';
COMMENT ON COLUMN sre_agent_run.ended_at IS '运行结束时间';
COMMENT ON COLUMN sre_agent_run.status_reason_code IS '状态原因码';
COMMENT ON COLUMN sre_agent_run.status_message IS '用户可见状态提示';
COMMENT ON COLUMN sre_agent_run.creation_date IS '创建时间';
COMMENT ON COLUMN sre_agent_run.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_agent_run.created_by IS '创建人工号';
COMMENT ON COLUMN sre_agent_run.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_agent_run.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE sre_scope_snapshot IS '运行时范围快照，只用于审计回放';
COMMENT ON COLUMN sre_scope_snapshot.scope_snapshot_id IS '范围快照主键';
COMMENT ON COLUMN sre_scope_snapshot.user_id IS '用户工号';
COMMENT ON COLUMN sre_scope_snapshot.agent_team_instance_id IS '所属实例 ID';
COMMENT ON COLUMN sre_scope_snapshot.agent_run_id IS '所属运行 ID';
COMMENT ON COLUMN sre_scope_snapshot.task_id IS '任务 ID，可空';
COMMENT ON COLUMN sre_scope_snapshot.workspace_id IS 'omodel 工作范围唯一标识';
COMMENT ON COLUMN sre_scope_snapshot.scope_revision IS 'resolve 时工作范围版本';
COMMENT ON COLUMN sre_scope_snapshot.effective_appids_snapshot IS 'omodel resolve 返回的 effective_appids 快照，不是权限事实源';
COMMENT ON COLUMN sre_scope_snapshot.omodel_request_id IS 'omodel 请求 ID';
COMMENT ON COLUMN sre_scope_snapshot.compute_reason IS 'session_create / task_start / tool_execution / recovery_tool_execute';
COMMENT ON COLUMN sre_scope_snapshot.computed_at IS '快照计算时间';
COMMENT ON COLUMN sre_scope_snapshot.creation_date IS '创建时间';
COMMENT ON COLUMN sre_scope_snapshot.created_by IS '创建人工号';
COMMENT ON COLUMN sre_scope_snapshot.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_scope_snapshot.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_scope_snapshot.expire_at IS '过期时间，供 30 天清理任务扫描';

COMMENT ON TABLE sre_approval_request IS 'AgentScope ASK/HITL 事件在 OpenOps PG 中的企业审计投影';
COMMENT ON COLUMN sre_approval_request.approval_request_id IS 'ASK 确认记录主键';
COMMENT ON COLUMN sre_approval_request.user_id IS '发起人工号';
COMMENT ON COLUMN sre_approval_request.agent_team_instance_id IS '所属实例 ID';
COMMENT ON COLUMN sre_approval_request.agent_run_id IS '所属运行 ID';
COMMENT ON COLUMN sre_approval_request.framework_session_id IS 'AgentScope session ID';
COMMENT ON COLUMN sre_approval_request.reply_id IS 'AgentScope RequireUserConfirmEvent reply_id';
COMMENT ON COLUMN sre_approval_request.tool_call_id IS 'AgentScope tool call id';
COMMENT ON COLUMN sre_approval_request.tool_call_name IS 'AgentScope tool 名称';
COMMENT ON COLUMN sre_approval_request.task_id IS '任务 ID，可空';
COMMENT ON COLUMN sre_approval_request.tool_catalog_id IS '准备调用的 tool catalog ID';
COMMENT ON COLUMN sre_approval_request.scope_snapshot_id IS '范围快照 ID';
COMMENT ON COLUMN sre_approval_request.arguments_redacted_json IS '脱敏参数摘要';
COMMENT ON COLUMN sre_approval_request.suggested_rules_redacted_json IS 'AgentScope suggested rules 脱敏摘要，仅审计，不生成长期策略';
COMMENT ON COLUMN sre_approval_request.decision IS 'pending / approved / rejected / timeout / cancelled';
COMMENT ON COLUMN sre_approval_request.decided_by IS '确认人工号';
COMMENT ON COLUMN sre_approval_request.decided_at IS '确认时间';
COMMENT ON COLUMN sre_approval_request.audit_trace_id IS '关联 trace';
COMMENT ON COLUMN sre_approval_request.creation_date IS '创建时间';
COMMENT ON COLUMN sre_approval_request.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_approval_request.created_by IS '创建人工号';
COMMENT ON COLUMN sre_approval_request.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_approval_request.expire_at IS 'ASK 确认超时时间，pending 超过即按 timeout 关闭';

COMMENT ON TABLE sre_audit_event IS 'OpenOps 结构化审计事件表';
COMMENT ON COLUMN sre_audit_event.audit_event_id IS '审计事件主键';
COMMENT ON COLUMN sre_audit_event.audit_trace_id IS '关联 trace 根 ID';
COMMENT ON COLUMN sre_audit_event.span_id IS '当前 span ID';
COMMENT ON COLUMN sre_audit_event.parent_span_id IS '父 span ID';
COMMENT ON COLUMN sre_audit_event.event_type IS '事件类型';
COMMENT ON COLUMN sre_audit_event.occurred_at IS '事件发生时间';
COMMENT ON COLUMN sre_audit_event.actor_type IS '动作发起方类型：user / system / agent';
COMMENT ON COLUMN sre_audit_event.user_id IS '关联用户工号，可空';
COMMENT ON COLUMN sre_audit_event.agent_team_instance_id IS '关联实例 ID，可空';
COMMENT ON COLUMN sre_audit_event.agent_run_id IS '关联运行 ID，可空';
COMMENT ON COLUMN sre_audit_event.task_id IS '关联任务 ID，可空';
COMMENT ON COLUMN sre_audit_event.config_version_id IS '关联配置版本 ID，可空';
COMMENT ON COLUMN sre_audit_event.scope_snapshot_id IS '关联范围快照 ID，可空';
COMMENT ON COLUMN sre_audit_event.target_type IS 'model / skill / mcp / omodel / approval / recovery_tool / sandbox / runtime_config';
COMMENT ON COLUMN sre_audit_event.target_id IS '目标对象标识，text 以兼容 uuid、tool 名、workspace_id 等多形态';
COMMENT ON COLUMN sre_audit_event.action IS '动作名';
COMMENT ON COLUMN sre_audit_event.decision IS 'allow / deny / pending / approved / rejected / timeout / cancelled / success / failed';
COMMENT ON COLUMN sre_audit_event.reason_code IS '原因码';
COMMENT ON COLUMN sre_audit_event.external_system IS '外部系统标识';
COMMENT ON COLUMN sre_audit_event.external_request_id IS '外部请求 ID';
COMMENT ON COLUMN sre_audit_event.payload_redacted_json IS '脱敏上下文';
COMMENT ON COLUMN sre_audit_event.payload_hash IS 'payload hash';
COMMENT ON COLUMN sre_audit_event.duration_ms IS '耗时毫秒';
COMMENT ON COLUMN sre_audit_event.created_by IS '创建人工号';
COMMENT ON COLUMN sre_audit_event.creation_date IS '创建时间';
COMMENT ON COLUMN sre_audit_event.last_update_date IS '最后更新时间';
COMMENT ON COLUMN sre_audit_event.last_updated_by IS '最后更新人工号';
COMMENT ON COLUMN sre_audit_event.expire_at IS '过期时间，V1 审计保留 30 天';

-- ==================== 增量迁移（幂等，重跑本文件自动补齐旧库） ====================
-- ⚠ 新列的 COMMENT 必须放本段（ALTER 之后）：COMMENT 无 IF EXISTS，放上方主体段会在旧库炸 UndefinedColumn。
-- 2026-07-12 会话名称（独立增量文件：migrate-2026-07-12-run-title.sql）
ALTER TABLE sre_agent_run ADD COLUMN IF NOT EXISTS run_title text;
COMMENT ON COLUMN sre_agent_run.run_title IS '会话名称：首个任务输入自动起名（前 30 字），用户可改；NULL=未起名（显示「新对话」）';
