-- OpenOps V1 core schema.
-- Rules: no foreign keys, no triggers, UUIDs are generated by the application.

CREATE TABLE IF NOT EXISTS openops_user (
  user_id uuid NOT NULL PRIMARY KEY,
  login_key text NOT NULL,
  display_name text NOT NULL,
  role text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_openops_user_login_key ON openops_user(login_key);

CREATE TABLE IF NOT EXISTS user_whitelist (
  whitelist_id uuid NOT NULL PRIMARY KEY,
  login_key text NOT NULL,
  role text NOT NULL,
  status text NOT NULL,
  created_by text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_whitelist_login_key ON user_whitelist(login_key);

CREATE TABLE IF NOT EXISTS platform_runtime_config (
  config_key text NOT NULL PRIMARY KEY,
  config_value_json jsonb NOT NULL,
  description text,
  updated_by text,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_team_template (
  template_id uuid NOT NULL PRIMARY KEY,
  template_key text NOT NULL,
  display_name text NOT NULL,
  description text,
  status text NOT NULL,
  created_by text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_agent_team_template_key ON agent_team_template(template_key);

CREATE TABLE IF NOT EXISTS agent_team_template_version (
  template_version_id uuid NOT NULL PRIMARY KEY,
  template_id uuid NOT NULL,
  version_no integer NOT NULL,
  content_json jsonb NOT NULL,
  status text NOT NULL,
  published_by text,
  published_at timestamptz,
  created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_agent_team_template_version_no ON agent_team_template_version(template_id, version_no);

CREATE TABLE IF NOT EXISTS agent_team_instance (
  agent_team_instance_id uuid NOT NULL PRIMARY KEY,
  owner_user_id uuid NOT NULL,
  instance_name text NOT NULL,
  template_id uuid NOT NULL,
  active_config_version_id uuid,
  workspace_id text NOT NULL,
  scope_revision text,
  run_status text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_agent_team_instance_owner_name ON agent_team_instance(owner_user_id, instance_name);
CREATE INDEX IF NOT EXISTS ix_agent_team_instance_owner ON agent_team_instance(owner_user_id);

CREATE TABLE IF NOT EXISTS agent_team_config_version (
  config_version_id uuid NOT NULL PRIMARY KEY,
  agent_team_instance_id uuid NOT NULL,
  template_version_id uuid NOT NULL,
  version_no integer NOT NULL,
  overlay_json jsonb NOT NULL,
  change_reason text,
  status text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_agent_team_config_version_no ON agent_team_config_version(agent_team_instance_id, version_no);
CREATE INDEX IF NOT EXISTS ix_agent_team_config_version_instance ON agent_team_config_version(agent_team_instance_id);

CREATE TABLE IF NOT EXISTS agent_team_instance_asset_binding (
  binding_id uuid NOT NULL PRIMARY KEY,
  agent_team_instance_id uuid NOT NULL,
  config_version_id uuid NOT NULL,
  asset_type text NOT NULL,
  asset_id uuid NOT NULL,
  asset_version_id uuid NOT NULL,
  agent_key text NOT NULL,
  status text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_instance_asset_binding_config ON agent_team_instance_asset_binding(config_version_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_instance_asset_binding_skill ON agent_team_instance_asset_binding(config_version_id, asset_version_id, agent_key) WHERE asset_type = 'skill';
CREATE UNIQUE INDEX IF NOT EXISTS ux_instance_asset_binding_mcp ON agent_team_instance_asset_binding(config_version_id, asset_version_id, agent_key) WHERE asset_type = 'mcp';

CREATE TABLE IF NOT EXISTS skill_asset (
  skill_id uuid NOT NULL PRIMARY KEY,
  source text NOT NULL DEFAULT 'openops',
  source_type text NOT NULL,
  owner_user_id uuid,
  skill_key text NOT NULL,
  display_name text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_skill_asset_source_status ON skill_asset(source, source_type, status);

CREATE TABLE IF NOT EXISTS skill_asset_version (
  skill_version_id uuid NOT NULL PRIMARY KEY,
  skill_id uuid NOT NULL,
  version_no text NOT NULL,
  package_uri text NOT NULL,
  checksum_sha256 text NOT NULL,
  manifest_json jsonb NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_skill_asset_version_no ON skill_asset_version(skill_id, version_no);

CREATE TABLE IF NOT EXISTS mcp_asset (
  mcp_id uuid NOT NULL PRIMARY KEY,
  source text NOT NULL DEFAULT 'openops',
  source_type text NOT NULL,
  owner_user_id uuid,
  mcp_key text NOT NULL,
  display_name text NOT NULL,
  transport text NOT NULL,
  endpoint_url text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_mcp_asset_source_status ON mcp_asset(source, source_type, status);

CREATE TABLE IF NOT EXISTS mcp_asset_version (
  mcp_version_id uuid NOT NULL PRIMARY KEY,
  mcp_id uuid NOT NULL,
  version_no text NOT NULL,
  endpoint_url text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_mcp_asset_version_no ON mcp_asset_version(mcp_id, version_no);

CREATE TABLE IF NOT EXISTS mcp_tool_catalog (
  tool_catalog_id uuid NOT NULL PRIMARY KEY,
  mcp_version_id uuid NOT NULL,
  tool_name text NOT NULL,
  display_name text NOT NULL,
  schema_json jsonb NOT NULL,
  schema_hash text NOT NULL,
  status text NOT NULL,
  discovered_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_mcp_tool_catalog_name ON mcp_tool_catalog(mcp_version_id, tool_name);

CREATE TABLE IF NOT EXISTS mcp_tool_annotation (
  annotation_id uuid NOT NULL PRIMARY KEY,
  tool_catalog_id uuid NOT NULL,
  is_approval_required boolean NOT NULL,
  is_secret_required boolean NOT NULL,
  scope_mode text NOT NULL,
  appid_arg_path text,
  status text NOT NULL,
  annotated_by uuid NOT NULL,
  annotated_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_mcp_tool_annotation_tool ON mcp_tool_annotation(tool_catalog_id);

CREATE TABLE IF NOT EXISTS user_secret (
  secret_ref_id uuid NOT NULL PRIMARY KEY,
  owner_user_id uuid NOT NULL,
  secret_name text NOT NULL,
  secret_kind text NOT NULL,
  encrypted_value bytea NOT NULL,
  fingerprint text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_user_secret_owner ON user_secret(owner_user_id, status);

CREATE TABLE IF NOT EXISTS user_llm_config (
  llm_config_id uuid NOT NULL PRIMARY KEY,
  owner_user_id uuid NOT NULL,
  display_name text NOT NULL,
  base_url text NOT NULL,
  model_name text NOT NULL,
  secret_ref_id uuid NOT NULL,
  context_window_tokens integer,
  max_output_tokens integer,
  timeout_ms integer,
  max_retries integer,
  supports_tool_calling boolean NOT NULL,
  supports_streaming boolean NOT NULL,
  supports_json_mode boolean NOT NULL,
  extra_params_json jsonb NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_user_llm_config_owner ON user_llm_config(owner_user_id, status);

CREATE TABLE IF NOT EXISTS agent_run (
  agent_run_id uuid NOT NULL PRIMARY KEY,
  agent_team_instance_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  config_version_id uuid NOT NULL,
  framework_session_id text NOT NULL,
  selected_model_ref text,
  run_status text NOT NULL,
  audit_trace_id text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  closed_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_agent_run_owner ON agent_run(owner_user_id, run_status);
CREATE INDEX IF NOT EXISTS ix_agent_run_trace ON agent_run(audit_trace_id);

CREATE TABLE IF NOT EXISTS scope_snapshot (
  scope_snapshot_id uuid NOT NULL PRIMARY KEY,
  agent_run_id uuid NOT NULL,
  task_id text,
  workspace_id text NOT NULL,
  scope_revision text,
  effective_appids_snapshot jsonb NOT NULL,
  compute_reason text NOT NULL,
  omodel_request_id text,
  computed_at timestamptz NOT NULL,
  expire_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_scope_snapshot_run ON scope_snapshot(agent_run_id, computed_at);

CREATE TABLE IF NOT EXISTS approval_request (
  approval_request_id uuid NOT NULL PRIMARY KEY,
  agent_run_id uuid NOT NULL,
  task_id text,
  framework_session_id text NOT NULL,
  reply_id text NOT NULL,
  tool_call_id text NOT NULL,
  tool_call_name text NOT NULL,
  arguments_redacted_json jsonb NOT NULL,
  suggested_rules_redacted_json jsonb NOT NULL,
  decision text NOT NULL,
  decided_by uuid,
  decided_at timestamptz,
  expire_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_approval_request_tool_call ON approval_request(agent_run_id, reply_id, tool_call_id);
CREATE INDEX IF NOT EXISTS ix_approval_request_decision ON approval_request(decision, expire_at);

CREATE TABLE IF NOT EXISTS audit_event (
  audit_event_id uuid NOT NULL PRIMARY KEY,
  audit_trace_id text NOT NULL,
  agent_run_id uuid,
  task_id text,
  actor_user_id uuid,
  event_type text NOT NULL,
  target_type text,
  target_id text,
  external_system text,
  external_request_id text,
  payload_redacted_json jsonb NOT NULL,
  occurred_at timestamptz NOT NULL,
  expire_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_event_trace ON audit_event(audit_trace_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_audit_event_run ON audit_event(agent_run_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_audit_event_expire ON audit_event(expire_at);
